### ISSUE TITLE
another bite at pg :)

### ISSUE THREAD

**Issue by vitaly-t** [sehrope/node-pg-db#2]
Nice work on your project here!

Although there seems to be so many packages for PG these days, I was tempted to publish one of my own, so I just did: https://github.com/vitaly-t/pg-promise
- that's specifically focusing on turning pg into being fully promise-based, which is very different from your library, so I hope the two can complement each other and cover every angle, each to anyone's liking.

One funny bit - we both chose <b>tx</b> as the namespace to transactions, although they work in a completely different way :)

Keep up good work! ;)

**Comment by sehrope** [comment]
Thanks!

I decided to use domains to implement transactions so that I could have completely separate modules join a transaction without having to pass around a context object. You can see a sample of using it [here](https://github.com/sehrope/node-pg-db-examples/blob/master/src/tx.coffee).

**Comment by vitaly-t** [comment]
The way I did it, you don't have to pass around a context object, the context is provided in place where it is needed. Other than that, I was just trying to support now standard Promises/A+.
