### ISSUE TITLE
Expose pool connection limit

### ISSUE THREAD

**Issue by meash-nrel** [sehrope/node-pg-db#3]
In reviewing src, we can pass in db client configuration into constructor that will be utilized in the lower level node-postgres initialization.

I wish to control the pool connection limit,  which node-postgres only exposes outside of configuration.(set by adjusting pg.defaults.poolSize after connection but before connect is called).

Is there a way to access that option in underlying node-postgres connection?  Or perhaps expose it by looking for a poolSize property in opts (constructor 2nd param).

**Comment by sehrope** [comment]
The `opts` second parameter is intended to eventually allow support for things like this. For this case, I'm not sure if it's necessary though.

The `pg` dependency for `pg-db` is setup as a peer dependency so you can modify it in your code and it will take effect in `pg-db` as well.

Example:

``` coffeescript
pg = require 'pg'
# Customize the connection pool size:
pg.defaults.poolSize = 2

async = require 'async'
doStuff = (i, cb) ->
  db.queryOne 'SELECT pg_sleep(1)', (err, row) ->
    console.log '%s - Completed query %s', new Date(), i
    cb(err)

db = require('pg-db')()
start = Date.now()
async.each [1..5], doStuff, (err, results) ->
  if err then return console.error(err)
  elapsed = Date.now() - start
  console.log 'Finished in %s ms', elapsed
  db.end()
```

Output with a pool size of 2:

```
Sat Apr 11 2015 15:16:47 GMT-0400 (EDT) - Completed query 1
Sat Apr 11 2015 15:16:47 GMT-0400 (EDT) - Completed query 2
Sat Apr 11 2015 15:16:48 GMT-0400 (EDT) - Completed query 3
Sat Apr 11 2015 15:16:48 GMT-0400 (EDT) - Completed query 4
Sat Apr 11 2015 15:16:49 GMT-0400 (EDT) - Completed query 5
Finished in 3014 ms
```

Output with a pool size of 10:

```
Sat Apr 11 2015 15:18:10 GMT-0400 (EDT) - Completed query 1
Sat Apr 11 2015 15:18:10 GMT-0400 (EDT) - Completed query 3
Sat Apr 11 2015 15:18:10 GMT-0400 (EDT) - Completed query 4
Sat Apr 11 2015 15:18:10 GMT-0400 (EDT) - Completed query 5
Sat Apr 11 2015 15:18:10 GMT-0400 (EDT) - Completed query 2
Finished in 1042 ms
```

**Comment by meash-nrel** [comment]
thanks for the workaround. closing.
