### ISSUE TITLE
Nodejs process remains in idle or lock status when execute an Query?

### ISSUE THREAD

**Issue by jmptrader** [sehrope/node-pg-db#4]
Dear,

I test your package, the next test code, run with results success, but the nodejs process remains in idle or lock status, only CTRL+C can end nodejs process, ¿ what can happen? 

Thanks for you help and attention. 

PD: I use the nodejs version 0.10.39 on CentOS 6.5, the postgres database is  version 9.4.

```
var db = require('pg-db')(
    { 
    host        : '10.0.204.63',
    port        : 5432,
    user        : 'postgres',
    database    : 'postgres',
    password    : 'postgres',
    }
);
db.query( 'SELECT * FROM table ', function(err, rows){
    if( err ) return console.error('Err: %s', err);
    console.log(rows);
});
```

**Comment by sehrope** [comment]
The underlying pool in node-postgres has an idle timeout of 30 seconds. You need to call `db.end()` to immediately close the open connections in the pool. Otherwise the node process will stay open until the idle connections are automatically cleared from the pool.

**Comment by jmptrader** [comment]
Thanks for your quickly response. was my mistake.
