### ISSUE TITLE
Retrieving inserted ID

### ISSUE THREAD

**Issue by rw3iss** [sehrope/node-pg-db#5]
Is there an easy way to retrieve the last inserted ID for a given update query?

**Comment by rw3iss** [comment]
Kinda hacked around it by editing lib/index.js in the node-pg-db module, and changing the update function just slightly (
Changed: 
        return cb(err, result != null ? result.rowCount : void 0);
To: 
        return cb(err, result != null ? result.rows : void 0);
(line 508)

So that it works when using 'INSERT blah RETURNING id'

**Comment by sehrope** [comment]
To get the generated ids back you should use the `.query(...)` method. You can use it with DML statements that return a value such as a RETURNING clause.

**Comment by rw3iss** [comment]
Ah, that makes sense... didn't think of it as a query ;p.
Thank you!
